import './globals.css'
import { cookies } from "next/headers"
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { SidebarWrapper } from "@/components/sidebar-wrapper"
import { Toaster } from './components/ui/toaster'
import { ThemeToggle } from './components/theme-toggle'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true"

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <div className="flex w-screen h-screen">
              <SidebarWrapper />
              <div className="flex-1 flex flex-col h-full">
                <header className="sticky top-0 flex h-16 shrink-0 items-center gap-2 bg-background px-4 justify-between z-10">
                  <SidebarTrigger className="-ml-1"/>
                  <ThemeToggle />
                </header>
                <main className="relative h-full w-full flex-1 overflow-auto">
                  {children}
                </main>
                <Toaster />
              </div>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout